package com.instisoft.form.views;

import java.awt.Color;
import java.awt.Cursor;
import java.awt.EventQueue;
import java.awt.Font;
import java.awt.SystemColor;
import java.awt.TextArea;
import java.sql.SQLException;

import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JTextArea;
import javax.swing.JTextField;
import javax.swing.JToggleButton;
import javax.swing.SwingConstants;
import javax.swing.border.EmptyBorder;

import com.instisoft.form.dto.BatchDTO;
import com.instisoft.form.helper.BatchHelper;
import com.instisoft.table.views.BatchTablePanel;
import com.instisoft.utils.GUILookAndFeel;

public class BatchFormPanel extends JPanel {


	private static final long serialVersionUID = 1L;
	
	private JTextField textField_Category;
	private JTextField textField_Faculty;
	private JTextField textField_Timing;
	private JTextField textField_Hours;
	
	private BatchDTO batchDTO;
	private BatchHelper batchHelper;
	private BatchTablePanel batchTablePanel;
	private JTextField textField_Name;
	private JTextField textField_Course;
	private JTextArea textArea_Desc;
	private JTextField textField_BatchId;
	private JTextField textField_StartDate;
	private JTextField textField_EndDate;
	
	{
		batchDTO = new BatchDTO();
		batchHelper = new BatchHelper();
		
		batchTablePanel = BatchTablePanel.newInstance();
	}
	
	

	public BatchFormPanel() {
	
		this.setSize(1118, 550);
		setLayout(null);
		setBackground(null);
		setOpaque(false);
		GUILookAndFeel.setGUILookAndFeel();
		
		JLabel lblName = new JLabel("Name of Batch  (optional)");
		lblName.setFont(new Font("Times New Roman", Font.PLAIN, 14));
		lblName.setForeground(Color.WHITE);
		lblName.setBounds(27, 11, 200, 23);
		add(lblName);
		
		textField_Name = new JTextField();
		textField_Name.setHorizontalAlignment(SwingConstants.LEFT);
		textField_Name.setFont(new Font("Times New Roman", Font.PLAIN, 14));
		textField_Name.setColumns(10);
		textField_Name.setBorder(new EmptyBorder(0, 10, 0, 10));
		textField_Name.setBounds(27, 36, 200, 30);
		add(textField_Name);
		
		JLabel lblAutoGeneratedSerialNo = new JLabel("Auto generated Batch Id");
		lblAutoGeneratedSerialNo.setForeground(Color.WHITE);
		lblAutoGeneratedSerialNo.setFont(new Font("Times New Roman", Font.PLAIN, 14));
		lblAutoGeneratedSerialNo.setBounds(438, 11, 157, 23);
		add(lblAutoGeneratedSerialNo);
		
		textField_BatchId = new JTextField();
		textField_BatchId.setEditable(false);
		textField_BatchId.setHorizontalAlignment(SwingConstants.LEFT);
		textField_BatchId.setFont(new Font("Times New Roman", Font.PLAIN, 14));
		textField_BatchId.setColumns(10);
		textField_BatchId.setBorder(new EmptyBorder(0, 10, 0, 10));
		textField_BatchId.setBounds(438, 36, 200, 30);
		add(textField_BatchId);
		
		JLabel lblCustomizeSno = new JLabel("Customize Batch Id");
		lblCustomizeSno.setForeground(Color.WHITE);
		lblCustomizeSno.setFont(new Font("Times New Roman", Font.PLAIN, 14));
		lblCustomizeSno.setBounds(719, 11, 134, 23);
		add(lblCustomizeSno);
		
		ImageIcon toggleOnIcon = new ImageIcon("resources/toggle_button_ON.png");
		ImageIcon toggleOffIcon =new ImageIcon("resources/toggle_button_OFF.png");
		
		JToggleButton toggleButton = new JToggleButton("OFF");
		toggleButton.setHorizontalAlignment(SwingConstants.LEADING);
		toggleButton.setForeground(GUILookAndFeel.getThemeColor());
		toggleButton.setFont(new Font("Trebuchet MS", Font.BOLD, 16));
		toggleButton.setFocusable(false);
		toggleButton.setContentAreaFilled(false);
		toggleButton.setOpaque(false);
		toggleButton.setBorderPainted(false);
		toggleButton.setBounds(719, 32, 134, 35);
		toggleButton.setIcon(toggleOffIcon);
		toggleButton.addItemListener((event)->{
			
			if(toggleButton.isSelected()){
				toggleButton.setText("ON");
				toggleButton.setIcon(toggleOnIcon);
				textField_BatchId.setEditable(true);
				
				
			}
			else{
				toggleButton.setText("OFF");
				toggleButton.setIcon(toggleOffIcon);
				textField_BatchId.setEditable(false);
				textField_BatchId.setFocusable(false);
				textField_BatchId.transferFocus();
				
			}
		});
		toggleButton.setCursor(new Cursor(Cursor.HAND_CURSOR));
		add(toggleButton);
		
		JLabel lblCourse = new JLabel("Select the Course");
		lblCourse.setForeground(Color.WHITE);
		lblCourse.setFont(new Font("Times New Roman", Font.PLAIN, 14));
		lblCourse.setBounds(27, 77, 123, 23);
		add(lblCourse);
		
		textField_Course = new JTextField();
		textField_Course.setHorizontalAlignment(SwingConstants.LEFT);
		textField_Course.setFont(new Font("Times New Roman", Font.PLAIN, 14));
		textField_Course.setColumns(10);
		textField_Course.setBorder(new EmptyBorder(0, 10, 0, 10));
		textField_Course.setBounds(27, 100, 200, 30);
		add(textField_Course);
		
		JLabel lblCategory = new JLabel("Batch Category");
		lblCategory.setForeground(Color.WHITE);
		lblCategory.setFont(new Font("Times New Roman", Font.PLAIN, 14));
		lblCategory.setBounds(27, 151, 114, 23);
		add(lblCategory);
		
		JLabel lbldesc = new JLabel("Description of Batch");
		lbldesc.setForeground(Color.WHITE);
		lbldesc.setFont(new Font("Times New Roman", Font.PLAIN, 14));
		lbldesc.setBounds(27, 221, 134, 23);
		add(lbldesc);
		
		textArea_Desc = new JTextArea();
		textArea_Desc.setBorder(new EmptyBorder(10, 10, 10, 10));
		textArea_Desc.setAlignmentX(TextArea.LEFT_ALIGNMENT);
		textArea_Desc.setFont(new Font("Times New Roman", Font.PLAIN, 14));
		textArea_Desc.setBounds(27, 245, 342, 93);
		add(textArea_Desc);
		
		JLabel lblStartDate = new JLabel("Batch Start Date");
		lblStartDate.setForeground(Color.WHITE);
		lblStartDate.setFont(new Font("Times New Roman", Font.PLAIN, 14));
		lblStartDate.setBounds(438, 77, 123, 23);
		add(lblStartDate);
		
		textField_StartDate = new JTextField();
		textField_StartDate.setHorizontalAlignment(SwingConstants.LEFT);
		textField_StartDate.setFont(new Font("Times New Roman", Font.PLAIN, 14));
		textField_StartDate.setColumns(10);
		textField_StartDate.setBorder(new EmptyBorder(0, 10, 0, 10));
		textField_StartDate.setBounds(438, 100, 200, 30);
		add(textField_StartDate);
		
		JLabel lblEndDate = new JLabel("Estimated End Date");
		lblEndDate.setForeground(Color.WHITE);
		lblEndDate.setFont(new Font("Times New Roman", Font.PLAIN, 14));
		lblEndDate.setBounds(438, 151, 140, 23);
		add(lblEndDate);
		
		textField_EndDate = new JTextField();
		textField_EndDate.setHorizontalAlignment(SwingConstants.LEFT);
		textField_EndDate.setFont(new Font("Times New Roman", Font.PLAIN, 14));
		textField_EndDate.setColumns(10);
		textField_EndDate.setBorder(new EmptyBorder(0, 10, 0, 10));
		textField_EndDate.setBounds(438, 173, 200, 30);
		add(textField_EndDate);
		
		JButton btnReset = new JButton("Reset");
		btnReset.setBackground(GUILookAndFeel.getThemeColor());
		btnReset.setForeground(Color.WHITE);
		btnReset.setFont(new Font("Tahoma", Font.PLAIN, 16));
		btnReset.setFocusPainted(false);
		btnReset.setBounds(668, 472, 185, 40);
		btnReset.addActionListener((event)->{
			resetFields();
		});
		add(btnReset);
		
		JButton btnSubmit = new JButton("Submit");
		btnSubmit.setBackground(GUILookAndFeel.getThemeColor());
		btnSubmit.setForeground(Color.WHITE);
		btnSubmit.setFont(new Font("Tahoma", Font.PLAIN, 16));
		btnSubmit.setFocusPainted(false);
		btnSubmit.setBounds(453, 472, 185, 40);
		btnSubmit.addActionListener((event)->{
			
			setFields();
			
			try {
				if(batchHelper.addBatch(batchDTO)){
					System.out.println("BATCH ADDED SUCCESSFULLY");
					
					
					batchTablePanel.renderBatchList();
					System.out.println("Table refreshed");
				
				}
				else{
					System.out.println("BATCH ENTRY UNSUCCESSFULL");
				}
			} catch (ClassNotFoundException | SQLException err) {
				
				err.printStackTrace();
			}
		
		});
		add(btnSubmit);
		
		textField_Category = new JTextField();
		textField_Category.setHorizontalAlignment(SwingConstants.LEFT);
		textField_Category.setFont(new Font("Times New Roman", Font.PLAIN, 14));
		textField_Category.setColumns(10);
		textField_Category.setBorder(new EmptyBorder(0, 10, 0, 10));
		textField_Category.setBounds(27, 173, 200, 30);
		add(textField_Category);
		
		JLabel lblFaculty = new JLabel("Choose Batch Faculty");
		lblFaculty.setForeground(Color.WHITE);
		lblFaculty.setFont(new Font("Times New Roman", Font.PLAIN, 14));
		lblFaculty.setBounds(27, 354, 157, 23);
		add(lblFaculty);
		
		textField_Faculty = new JTextField();
		textField_Faculty.setHorizontalAlignment(SwingConstants.LEFT);
		textField_Faculty.setFont(new Font("Times New Roman", Font.PLAIN, 14));
		textField_Faculty.setColumns(10);
		textField_Faculty.setBorder(new EmptyBorder(0, 10, 0, 10));
		textField_Faculty.setBounds(27, 378, 200, 30);
		add(textField_Faculty);
		
		JLabel lblTiming = new JLabel("Batch Timing");
		lblTiming.setForeground(Color.WHITE);
		lblTiming.setFont(new Font("Times New Roman", Font.PLAIN, 14));
		lblTiming.setBounds(438, 221, 140, 23);
		add(lblTiming);
		
		textField_Timing = new JTextField();
		textField_Timing.setHorizontalAlignment(SwingConstants.LEFT);
		textField_Timing.setFont(new Font("Times New Roman", Font.PLAIN, 14));
		textField_Timing.setColumns(10);
		textField_Timing.setBorder(new EmptyBorder(0, 10, 0, 10));
		textField_Timing.setBounds(438, 245, 200, 30);
		add(textField_Timing);
		
		JLabel lbl_Classes = new JLabel("Set Hours per Class");
		lbl_Classes.setForeground(Color.WHITE);
		lbl_Classes.setFont(new Font("Times New Roman", Font.PLAIN, 14));
		lbl_Classes.setBounds(438, 288, 140, 23);
		add(lbl_Classes);
		
		textField_Hours = new JTextField();
		textField_Hours.setHorizontalAlignment(SwingConstants.LEFT);
		textField_Hours.setFont(new Font("Times New Roman", Font.PLAIN, 14));
		textField_Hours.setColumns(10);
		textField_Hours.setBorder(new EmptyBorder(0, 10, 0, 10));
		textField_Hours.setBounds(438, 311, 200, 30);
		add(textField_Hours);
	}
	
	private void resetFields(){
		textField_BatchId.setText("");
		textField_Name.setText("");
		textField_Course.setText("");
		textField_Category.setText("");
		textField_Faculty.setText("");
		textField_StartDate.setText("");
		textField_EndDate.setText("");
		textField_Timing.setText("");
		textField_Hours.setText("");
	}
	
	private void setFields(){
		batchDTO.setId(textField_BatchId.getText());
		batchDTO.setName(textField_Name.getText());
		batchDTO.setCourseId(textField_Course.getText());
		batchDTO.setCategory(textField_Category.getText());
		batchDTO.setFaculty(null);
		batchDTO.setStartDate(textField_StartDate.getText());
		batchDTO.setEndDate(textField_EndDate.getText());
		batchDTO.setTime(textField_Timing.getText());
		batchDTO.setHours(Integer.parseInt(textField_Hours.getText()));
	}
	
	/**
	 * Launch the application.
	 */
	public static void main(String[] args) {
		EventQueue.invokeLater(new Runnable() {
			public void run() {
				try {
					JFrame frame = new JFrame();
					frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
					frame.setBounds(100, 100, 1400, 1000);
					frame.setExtendedState(JFrame.MAXIMIZED_BOTH);
					frame.getContentPane().setLayout(null);
					frame.setBackground(Color.GRAY);
					
					JPanel contentPane = new JPanel();
					contentPane.setBackground(SystemColor.windowBorder);
					contentPane.setBorder(new EmptyBorder(5, 5, 5, 5));
					contentPane.setLayout(null);
					contentPane.add(new BatchFormPanel());
					frame.setContentPane(contentPane);
					
					
					frame.setVisible(true);
					
				} catch (Exception e) {
					e.printStackTrace();
				}
			}
		});
	}

}
