package com.instisoft.form.views;

import java.awt.Color;
import java.awt.Cursor;
import java.awt.EventQueue;
import java.awt.Font;
import java.awt.SystemColor;
import java.awt.TextArea;

import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JTextArea;
import javax.swing.JTextField;
import javax.swing.JToggleButton;
import javax.swing.SwingConstants;
import javax.swing.border.EmptyBorder;

import com.instisoft.utils.GUILookAndFeel;

public class BatchFormPanel extends JPanel {


	private static final long serialVersionUID = 1L;
	private JTextField textField;
	private JTextField textField_Faculty;
	private JTextField textField_Timing;
	private JTextField textField_Hours;

	public BatchFormPanel() {
	
		this.setSize(1118, 550);
		setLayout(null);
		setBackground(null);
		setOpaque(false);
		GUILookAndFeel.setGUILookAndFeel();
		
		JLabel lblName = new JLabel("Name of Batch  (optional)");
		lblName.setFont(new Font("Times New Roman", Font.PLAIN, 14));
		lblName.setForeground(Color.WHITE);
		lblName.setBounds(27, 11, 200, 23);
		add(lblName);
		
		JTextField textField_name = new JTextField();
		textField_name.setHorizontalAlignment(SwingConstants.LEFT);
		textField_name.setFont(new Font("Times New Roman", Font.PLAIN, 14));
		textField_name.setColumns(10);
		textField_name.setBorder(new EmptyBorder(0, 10, 0, 10));
		textField_name.setBounds(27, 36, 200, 30);
		add(textField_name);
		
		JLabel lblAutoGeneratedSerialNo = new JLabel("Auto generated Batch Id");
		lblAutoGeneratedSerialNo.setForeground(Color.WHITE);
		lblAutoGeneratedSerialNo.setFont(new Font("Times New Roman", Font.PLAIN, 14));
		lblAutoGeneratedSerialNo.setBounds(438, 11, 157, 23);
		add(lblAutoGeneratedSerialNo);
		
		JTextField textField_eventid = new JTextField();
		textField_eventid.setEditable(false);
		textField_eventid.setHorizontalAlignment(SwingConstants.LEFT);
		textField_eventid.setFont(new Font("Times New Roman", Font.PLAIN, 14));
		textField_eventid.setColumns(10);
		textField_eventid.setBorder(new EmptyBorder(0, 10, 0, 10));
		textField_eventid.setBounds(438, 36, 200, 30);
		add(textField_eventid);
		
		JLabel lblCustomizeSno = new JLabel("Customize Batch Id");
		lblCustomizeSno.setForeground(Color.WHITE);
		lblCustomizeSno.setFont(new Font("Times New Roman", Font.PLAIN, 14));
		lblCustomizeSno.setBounds(719, 11, 134, 23);
		add(lblCustomizeSno);
		
		ImageIcon toggleOnIcon = new ImageIcon("resources/toggle_button_ON.png");
		ImageIcon toggleOffIcon =new ImageIcon("resources/toggle_button_OFF.png");
		
		JToggleButton toggleButton = new JToggleButton("OFF");
		toggleButton.setHorizontalAlignment(SwingConstants.LEADING);
		toggleButton.setForeground(GUILookAndFeel.getThemeColor());
		toggleButton.setFont(new Font("Trebuchet MS", Font.BOLD, 16));
		toggleButton.setFocusable(false);
		toggleButton.setContentAreaFilled(false);
		toggleButton.setOpaque(false);
		toggleButton.setBorderPainted(false);
		toggleButton.setBounds(719, 32, 134, 35);
		toggleButton.setIcon(toggleOffIcon);
		toggleButton.addItemListener((event)->{
			
			if(toggleButton.isSelected()){
				toggleButton.setText("ON");
				toggleButton.setIcon(toggleOnIcon);
				textField_eventid.setEditable(true);
				
				
			}
			else{
				toggleButton.setText("OFF");
				toggleButton.setIcon(toggleOffIcon);
				textField_eventid.setEditable(false);
				textField_eventid.setFocusable(false);
				textField_eventid.transferFocus();
				
			}
		});
		toggleButton.setCursor(new Cursor(Cursor.HAND_CURSOR));
		add(toggleButton);
		
		JLabel lblCourse = new JLabel("Select the Course");
		lblCourse.setForeground(Color.WHITE);
		lblCourse.setFont(new Font("Times New Roman", Font.PLAIN, 14));
		lblCourse.setBounds(27, 77, 123, 23);
		add(lblCourse);
		
		JTextField textField_course = new JTextField();
		textField_course.setHorizontalAlignment(SwingConstants.LEFT);
		textField_course.setFont(new Font("Times New Roman", Font.PLAIN, 14));
		textField_course.setColumns(10);
		textField_course.setBorder(new EmptyBorder(0, 10, 0, 10));
		textField_course.setBounds(27, 100, 200, 30);
		add(textField_course);
		
		JLabel lblCategory = new JLabel("Batch Category");
		lblCategory.setForeground(Color.WHITE);
		lblCategory.setFont(new Font("Times New Roman", Font.PLAIN, 14));
		lblCategory.setBounds(27, 151, 114, 23);
		add(lblCategory);
		
		JLabel lbldesc = new JLabel("Description of Batch");
		lbldesc.setForeground(Color.WHITE);
		lbldesc.setFont(new Font("Times New Roman", Font.PLAIN, 14));
		lbldesc.setBounds(27, 221, 134, 23);
		add(lbldesc);
		
		JTextArea textArea_desc = new JTextArea();
		textArea_desc.setBorder(new EmptyBorder(10, 10, 10, 10));
		textArea_desc.setAlignmentX(TextArea.LEFT_ALIGNMENT);
		textArea_desc.setFont(new Font("Times New Roman", Font.PLAIN, 14));
		textArea_desc.setBounds(27, 245, 342, 93);
		add(textArea_desc);
		
		JLabel lblStartDate = new JLabel("Batch Start Date");
		lblStartDate.setForeground(Color.WHITE);
		lblStartDate.setFont(new Font("Times New Roman", Font.PLAIN, 14));
		lblStartDate.setBounds(438, 77, 123, 23);
		add(lblStartDate);
		
		JTextField textField_time = new JTextField();
		textField_time.setHorizontalAlignment(SwingConstants.LEFT);
		textField_time.setFont(new Font("Times New Roman", Font.PLAIN, 14));
		textField_time.setColumns(10);
		textField_time.setBorder(new EmptyBorder(0, 10, 0, 10));
		textField_time.setBounds(438, 100, 200, 30);
		add(textField_time);
		
		JLabel lblEndDate = new JLabel("Estimated End Date");
		lblEndDate.setForeground(Color.WHITE);
		lblEndDate.setFont(new Font("Times New Roman", Font.PLAIN, 14));
		lblEndDate.setBounds(438, 151, 140, 23);
		add(lblEndDate);
		
		JTextField textField_status = new JTextField();
		textField_status.setHorizontalAlignment(SwingConstants.LEFT);
		textField_status.setFont(new Font("Times New Roman", Font.PLAIN, 14));
		textField_status.setColumns(10);
		textField_status.setBorder(new EmptyBorder(0, 10, 0, 10));
		textField_status.setBounds(438, 173, 200, 30);
		add(textField_status);
		
		JButton btnReset = new JButton("Reset");
		btnReset.setBackground(GUILookAndFeel.getThemeColor());
		btnReset.setForeground(Color.WHITE);
		btnReset.setFont(new Font("Tahoma", Font.PLAIN, 16));
		btnReset.setFocusPainted(false);
		btnReset.setBounds(668, 472, 185, 40);
		add(btnReset);
		
		JButton btnSubmit = new JButton("Submit");
		btnSubmit.setBackground(GUILookAndFeel.getThemeColor());
		btnSubmit.setForeground(Color.WHITE);
		btnSubmit.setFont(new Font("Tahoma", Font.PLAIN, 16));
		btnSubmit.setFocusPainted(false);
		btnSubmit.setBounds(453, 472, 185, 40);
		add(btnSubmit);
		
		textField = new JTextField();
		textField.setHorizontalAlignment(SwingConstants.LEFT);
		textField.setFont(new Font("Times New Roman", Font.PLAIN, 14));
		textField.setColumns(10);
		textField.setBorder(new EmptyBorder(0, 10, 0, 10));
		textField.setBounds(27, 173, 200, 30);
		add(textField);
		
		JLabel lblFaculty = new JLabel("Choose Batch Faculty");
		lblFaculty.setForeground(Color.WHITE);
		lblFaculty.setFont(new Font("Times New Roman", Font.PLAIN, 14));
		lblFaculty.setBounds(27, 354, 157, 23);
		add(lblFaculty);
		
		textField_Faculty = new JTextField();
		textField_Faculty.setHorizontalAlignment(SwingConstants.LEFT);
		textField_Faculty.setFont(new Font("Times New Roman", Font.PLAIN, 14));
		textField_Faculty.setColumns(10);
		textField_Faculty.setBorder(new EmptyBorder(0, 10, 0, 10));
		textField_Faculty.setBounds(27, 378, 200, 30);
		add(textField_Faculty);
		
		JLabel lblTiming = new JLabel("Batch Timing");
		lblTiming.setForeground(Color.WHITE);
		lblTiming.setFont(new Font("Times New Roman", Font.PLAIN, 14));
		lblTiming.setBounds(438, 221, 140, 23);
		add(lblTiming);
		
		textField_Timing = new JTextField();
		textField_Timing.setHorizontalAlignment(SwingConstants.LEFT);
		textField_Timing.setFont(new Font("Times New Roman", Font.PLAIN, 14));
		textField_Timing.setColumns(10);
		textField_Timing.setBorder(new EmptyBorder(0, 10, 0, 10));
		textField_Timing.setBounds(438, 245, 200, 30);
		add(textField_Timing);
		
		JLabel lbl_Classes = new JLabel("Set Hours per Class");
		lbl_Classes.setForeground(Color.WHITE);
		lbl_Classes.setFont(new Font("Times New Roman", Font.PLAIN, 14));
		lbl_Classes.setBounds(438, 288, 140, 23);
		add(lbl_Classes);
		
		textField_Hours = new JTextField();
		textField_Hours.setHorizontalAlignment(SwingConstants.LEFT);
		textField_Hours.setFont(new Font("Times New Roman", Font.PLAIN, 14));
		textField_Hours.setColumns(10);
		textField_Hours.setBorder(new EmptyBorder(0, 10, 0, 10));
		textField_Hours.setBounds(438, 311, 200, 30);
		add(textField_Hours);
	}
	
	/**
	 * Launch the application.
	 */
	public static void main(String[] args) {
		EventQueue.invokeLater(new Runnable() {
			public void run() {
				try {
					JFrame frame = new JFrame();
					frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
					frame.setBounds(100, 100, 1400, 1000);
					frame.setExtendedState(JFrame.MAXIMIZED_BOTH);
					frame.getContentPane().setLayout(null);
					frame.setBackground(Color.GRAY);
					
					JPanel contentPane = new JPanel();
					contentPane.setBackground(SystemColor.windowBorder);
					contentPane.setBorder(new EmptyBorder(5, 5, 5, 5));
					contentPane.setLayout(null);
					contentPane.add(new BatchFormPanel());
					frame.setContentPane(contentPane);
					
					
					frame.setVisible(true);
					
				} catch (Exception e) {
					e.printStackTrace();
				}
			}
		});
	}

}
