package com.instisoft.form.views;

import java.awt.Color;
import java.awt.Cursor;
import java.awt.EventQueue;
import java.awt.Font;
import java.awt.SystemColor;
import java.awt.TextArea;
import java.sql.SQLException;

import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JTextArea;
import javax.swing.JTextField;
import javax.swing.JToggleButton;
import javax.swing.SwingConstants;
import javax.swing.border.EmptyBorder;

import com.instisoft.form.dto.CourseDTO;
import com.instisoft.form.helper.CourseHelper;
import com.instisoft.table.views.CourseTablePanel;
import com.instisoft.utils.GUILookAndFeel;

public class CourseFormPanel extends JPanel {

	
	private static final long serialVersionUID = 1L;
	
	private CourseDTO courseDTO;
	private CourseHelper courseHelper;
	private CourseTablePanel courseTablePanel;
	
	private JTextField textField_Fee;
	private JTextField textField_Name;
	private JTextField textField_Faculty;
	private JTextField textField_Schedule;
	private JTextField textField_Classes;
	private JTextField textField_Category;
	private JTextField textField_CourseId;
	private JTextArea textArea_Desc;
	
	{
		courseDTO = new CourseDTO();
		courseHelper = new CourseHelper();
		
		courseTablePanel = CourseTablePanel.newInstance();
	}

	public CourseFormPanel() {
	
		setSize(1118, 550);
		setLayout(null);
		setBackground(null);
		setOpaque(false);
		
		
		JLabel lblName = new JLabel("Name of Course");
		lblName.setFont(new Font("Times New Roman", Font.PLAIN, 14));
		lblName.setForeground(Color.WHITE);
		lblName.setBounds(27, 11, 200, 23);
		add(lblName);
		
		textField_Name = new JTextField();
		textField_Name.setHorizontalAlignment(SwingConstants.LEFT);
		textField_Name.setFont(new Font("Times New Roman", Font.PLAIN, 14));
		textField_Name.setColumns(10);
		textField_Name.setBorder(new EmptyBorder(0, 10, 0, 10));
		textField_Name.setBounds(27, 36, 200, 30);
		add(textField_Name);
		
		JLabel lblAutoGeneratedSerialNo = new JLabel("Auto generated Course Id");
		lblAutoGeneratedSerialNo.setForeground(Color.WHITE);
		lblAutoGeneratedSerialNo.setFont(new Font("Times New Roman", Font.PLAIN, 14));
		lblAutoGeneratedSerialNo.setBounds(438, 11, 157, 23);
		add(lblAutoGeneratedSerialNo);
		
		textField_CourseId = new JTextField();
		textField_CourseId.setEditable(false);
		textField_CourseId.setHorizontalAlignment(SwingConstants.LEFT);
		textField_CourseId.setFont(new Font("Times New Roman", Font.PLAIN, 14));
		textField_CourseId.setColumns(10);
		textField_CourseId.setBorder(new EmptyBorder(0, 10, 0, 10));
		textField_CourseId.setBounds(438, 36, 200, 30);
		add(textField_CourseId);
		
		JLabel lblCustomizeSno = new JLabel("Customize Course Id");
		lblCustomizeSno.setForeground(Color.WHITE);
		lblCustomizeSno.setFont(new Font("Times New Roman", Font.PLAIN, 14));
		lblCustomizeSno.setBounds(719, 11, 134, 23);
		add(lblCustomizeSno);
		
		ImageIcon toggleOnIcon = new ImageIcon("resources/toggle_button_ON.png");
		ImageIcon toggleOffIcon =new ImageIcon("resources/toggle_button_OFF.png");
		
		JToggleButton toggleButton = new JToggleButton("OFF");
		toggleButton.setHorizontalAlignment(SwingConstants.LEADING);
		toggleButton.setForeground(GUILookAndFeel.getThemeColor());
		toggleButton.setFont(new Font("Trebuchet MS", Font.BOLD, 16));
		toggleButton.setFocusable(false);
		toggleButton.setContentAreaFilled(false);
		toggleButton.setOpaque(false);
		toggleButton.setBorderPainted(false);
		toggleButton.setBounds(719, 32, 134, 35);
		toggleButton.setIcon(toggleOffIcon);
		toggleButton.addItemListener((event)->{
			
			if(toggleButton.isSelected()){
				toggleButton.setText("ON");
				toggleButton.setIcon(toggleOnIcon);
				textField_CourseId.setEditable(true);
				
				
			}
			else{
				toggleButton.setText("OFF");
				toggleButton.setIcon(toggleOffIcon);
				textField_CourseId.setEditable(false);
				textField_CourseId.setFocusable(false);
				textField_CourseId.transferFocus();
				
			}
		});
		toggleButton.setCursor(new Cursor(Cursor.HAND_CURSOR));
		add(toggleButton);
		
		JLabel lblCategory = new JLabel("Course Category");
		lblCategory.setForeground(Color.WHITE);
		lblCategory.setFont(new Font("Times New Roman", Font.PLAIN, 14));
		lblCategory.setBounds(27, 77, 123, 23);
		add(lblCategory);
		
		textField_Category = new JTextField();
		textField_Category.setHorizontalAlignment(SwingConstants.LEFT);
		textField_Category.setFont(new Font("Times New Roman", Font.PLAIN, 14));
		textField_Category.setColumns(10);
		textField_Category.setBorder(new EmptyBorder(0, 10, 0, 10));
		textField_Category.setBounds(27, 100, 200, 30);
		add(textField_Category);
		
		JLabel lblFee = new JLabel("Course fee");
		lblFee.setForeground(Color.WHITE);
		lblFee.setFont(new Font("Times New Roman", Font.PLAIN, 14));
		lblFee.setBounds(27, 151, 100, 23);
		add(lblFee);
		
		JLabel lbldesc = new JLabel("Description of Course");
		lbldesc.setForeground(Color.WHITE);
		lbldesc.setFont(new Font("Times New Roman", Font.PLAIN, 14));
		lbldesc.setBounds(27, 221, 134, 23);
		add(lbldesc);
		
		textArea_Desc = new JTextArea();
		textArea_Desc.setBorder(new EmptyBorder(10, 10, 10, 10));
		textArea_Desc.setAlignmentX(TextArea.LEFT_ALIGNMENT);
		textArea_Desc.setFont(new Font("Times New Roman", Font.PLAIN, 14));
		textArea_Desc.setBounds(27, 245, 342, 93);
		add(textArea_Desc);
		
		JButton btnReset = new JButton("Reset");
		btnReset.setBackground(GUILookAndFeel.getThemeColor());
		btnReset.setForeground(Color.WHITE);
		btnReset.setFont(new Font("Tahoma", Font.PLAIN, 16));
		btnReset.setFocusPainted(false);
		btnReset.setBounds(668, 472, 185, 40);
		btnReset.addActionListener((event)->{
			resetFields();
		});
		add(btnReset);
		
		JButton btnSubmit = new JButton("Submit");
		btnSubmit.setBackground(GUILookAndFeel.getThemeColor());
		btnSubmit.setForeground(Color.WHITE);
		btnSubmit.setFont(new Font("Tahoma", Font.PLAIN, 16));
		btnSubmit.setFocusPainted(false);
		btnSubmit.setBounds(453, 472, 185, 40);
		btnSubmit.addActionListener((event)->{
			
			setFields();
			
			try {
				if(courseHelper.addCourse(courseDTO)){
					System.out.println("COURSE ADDED SUCCESSFULLY");
					
					
					courseTablePanel.renderCourseList();
					System.out.println("Table refreshed");
				
				}
				else{
					System.out.println("COURSE ENTRY UNSUCCESSFULL");
				}
			} catch (ClassNotFoundException | SQLException err) {
				
				err.printStackTrace();
			}
		
		});
		add(btnSubmit);
		
		textField_Fee = new JTextField();
		textField_Fee.setHorizontalAlignment(SwingConstants.LEFT);
		textField_Fee.setFont(new Font("Times New Roman", Font.PLAIN, 14));
		textField_Fee.setColumns(10);
		textField_Fee.setBorder(new EmptyBorder(0, 10, 0, 10));
		textField_Fee.setBounds(27, 173, 200, 30);
		add(textField_Fee);
		
		JLabel lblFaculty = new JLabel("Faculty Name");
		lblFaculty.setForeground(Color.WHITE);
		lblFaculty.setFont(new Font("Times New Roman", Font.PLAIN, 14));
		lblFaculty.setBounds(27, 354, 140, 23);
		add(lblFaculty);
		
		textField_Faculty = new JTextField();
		textField_Faculty.setHorizontalAlignment(SwingConstants.LEFT);
		textField_Faculty.setFont(new Font("Times New Roman", Font.PLAIN, 14));
		textField_Faculty.setColumns(10);
		textField_Faculty.setBorder(new EmptyBorder(0, 10, 0, 10));
		textField_Faculty.setBounds(27, 378, 200, 30);
		add(textField_Faculty);
		
		JLabel lblSchedule = new JLabel("Batch Schedule");
		lblSchedule.setForeground(Color.WHITE);
		lblSchedule.setFont(new Font("Times New Roman", Font.PLAIN, 14));
		lblSchedule.setBounds(438, 151, 140, 23);
		add(lblSchedule);
		
		textField_Schedule = new JTextField();
		textField_Schedule.setHorizontalAlignment(SwingConstants.LEFT);
		textField_Schedule.setFont(new Font("Times New Roman", Font.PLAIN, 14));
		textField_Schedule.setColumns(10);
		textField_Schedule.setBorder(new EmptyBorder(0, 10, 0, 10));
		textField_Schedule.setBounds(438, 173, 200, 30);
		add(textField_Schedule);
		
		JLabel lbl_Classes = new JLabel("Number of Classes");
		lbl_Classes.setForeground(Color.WHITE);
		lbl_Classes.setFont(new Font("Times New Roman", Font.PLAIN, 14));
		lbl_Classes.setBounds(438, 77, 140, 23);
		add(lbl_Classes);
		
		textField_Classes = new JTextField();
		textField_Classes.setHorizontalAlignment(SwingConstants.LEFT);
		textField_Classes.setFont(new Font("Times New Roman", Font.PLAIN, 14));
		textField_Classes.setColumns(10);
		textField_Classes.setBorder(new EmptyBorder(0, 10, 0, 10));
		textField_Classes.setBounds(438, 100, 200, 30);
		add(textField_Classes);
	}
	
	private void resetFields(){
		textField_CourseId.setText("");
		textField_Name.setText("");
		textField_Category.setText("");
		textField_Fee.setText("");
		textField_Faculty.setText("");
		textField_Classes.setText("");
		textField_Schedule.setText("");
		textArea_Desc.setText("");
	}
	
	private void setFields(){
		courseDTO.setId(textField_CourseId.getText());
		courseDTO.setName(textField_Name.getText());
		courseDTO.setCategory(textField_Category.getText());
		courseDTO.setCourceFee(Double.parseDouble(textField_Fee.getText()));
		courseDTO.setFacultySet(null); 			// null For the Faculty
		courseDTO.setTotalClasses(Integer.parseInt(textField_Classes.getText()));
		courseDTO.setBatchSchedule(textField_Schedule.getText());
	}
	
	/**
	 * Launch the application.
	 */
	public static void main(String[] args) {
		EventQueue.invokeLater(new Runnable() {
			public void run() {
				try {
					JFrame frame = new JFrame();
					frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
					frame.setBounds(100, 100, 1400, 1000);
					frame.setExtendedState(JFrame.MAXIMIZED_BOTH);
					frame.getContentPane().setLayout(null);
					frame.setBackground(Color.GRAY);
					
					JPanel contentPane = new JPanel();
					contentPane.setBackground(SystemColor.windowBorder);
					contentPane.setBorder(new EmptyBorder(5, 5, 5, 5));
					contentPane.setLayout(null);
					contentPane.add(new CourseFormPanel());
					frame.setContentPane(contentPane);
					
					
					frame.setVisible(true);
					
				} catch (Exception e) {
					e.printStackTrace();
				}
			}
		});
	}
}
