package com.instisoft.form.views;

import java.awt.Color;
import java.awt.Cursor;
import java.awt.EventQueue;
import java.awt.Font;
import java.awt.SystemColor;
import java.awt.TextArea;

import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JTextArea;
import javax.swing.JTextField;
import javax.swing.JToggleButton;
import javax.swing.SwingConstants;
import javax.swing.border.EmptyBorder;

public class EventFormPanel extends JPanel {


	private static final long serialVersionUID = 1L;

	public EventFormPanel() {
	
		this.setSize(1118, 550);
		setLayout(null);
		setBackground(null);
		setOpaque(false);
		
		
		JLabel lblName = new JLabel("Name of Event");
		lblName.setFont(new Font("Times New Roman", Font.PLAIN, 14));
		lblName.setForeground(Color.WHITE);
		lblName.setBounds(27, 11, 200, 23);
		add(lblName);
		
		JTextField textField_name = new JTextField();
		textField_name.setHorizontalAlignment(SwingConstants.LEFT);
		textField_name.setFont(new Font("Times New Roman", Font.PLAIN, 14));
		textField_name.setColumns(10);
		textField_name.setBorder(new EmptyBorder(0, 10, 0, 10));
		textField_name.setBounds(27, 36, 200, 30);
		add(textField_name);
		
		JLabel lblAutoGeneratedSerialNo = new JLabel("Auto generated Event Id");
		lblAutoGeneratedSerialNo.setForeground(Color.WHITE);
		lblAutoGeneratedSerialNo.setFont(new Font("Times New Roman", Font.PLAIN, 14));
		lblAutoGeneratedSerialNo.setBounds(429, 11, 157, 23);
		add(lblAutoGeneratedSerialNo);
		
		JTextField textField_eventid = new JTextField();
		textField_eventid.setEditable(false);
		textField_eventid.setHorizontalAlignment(SwingConstants.LEFT);
		textField_eventid.setFont(new Font("Times New Roman", Font.PLAIN, 14));
		textField_eventid.setColumns(10);
		textField_eventid.setBorder(new EmptyBorder(0, 10, 0, 10));
		textField_eventid.setBounds(426, 36, 200, 30);
		add(textField_eventid);
		
		JLabel lblCustomizeSno = new JLabel("Customize Event Id");
		lblCustomizeSno.setForeground(Color.WHITE);
		lblCustomizeSno.setFont(new Font("Times New Roman", Font.PLAIN, 14));
		lblCustomizeSno.setBounds(719, 11, 134, 23);
		add(lblCustomizeSno);
		
		ImageIcon toggleOnIcon = new ImageIcon("resources/toggle_button_ON.png");
		ImageIcon toggleOffIcon =new ImageIcon("resources/toggle_button_OFF.png");
		
		JToggleButton toggleButton = new JToggleButton("OFF");
		toggleButton.setHorizontalAlignment(SwingConstants.LEADING);
		toggleButton.setForeground(new Color(102, 255, 153));
		toggleButton.setFont(new Font("Trebuchet MS", Font.BOLD, 16));
		toggleButton.setFocusable(false);
		toggleButton.setContentAreaFilled(false);
		toggleButton.setOpaque(false);
		toggleButton.setBorderPainted(false);
		toggleButton.setBounds(719, 32, 134, 35);
		toggleButton.setIcon(toggleOffIcon);
		toggleButton.addItemListener((event)->{
			
			if(toggleButton.isSelected()){
				toggleButton.setText("ON");
				toggleButton.setIcon(toggleOnIcon);
				textField_eventid.setEditable(true);
				
				
			}
			else{
				toggleButton.setText("OFF");
				toggleButton.setIcon(toggleOffIcon);
				textField_eventid.setFocusable(false);
				textField_eventid.setEditable(false);
				textField_eventid.transferFocus();
				
			}
		});
		toggleButton.setCursor(new Cursor(Cursor.HAND_CURSOR));
		add(toggleButton);
		
		JLabel lblDate = new JLabel("Date of Event");
		lblDate.setForeground(Color.WHITE);
		lblDate.setFont(new Font("Times New Roman", Font.PLAIN, 14));
		lblDate.setBounds(27, 77, 89, 23);
		add(lblDate);
		
		JTextField textField_date = new JTextField();
		textField_date.setHorizontalAlignment(SwingConstants.LEFT);
		textField_date.setFont(new Font("Times New Roman", Font.PLAIN, 14));
		textField_date.setColumns(10);
		textField_date.setBorder(new EmptyBorder(0, 10, 0, 10));
		textField_date.setBounds(27, 100, 200, 30);
		add(textField_date);
		
		JLabel lblvenue = new JLabel("Venue");
		lblvenue.setForeground(Color.WHITE);
		lblvenue.setFont(new Font("Times New Roman", Font.PLAIN, 14));
		lblvenue.setBounds(27, 151, 100, 23);
		add(lblvenue);
		
		JTextArea textArea_venue = new JTextArea();
		textArea_venue.setBorder(new EmptyBorder(10, 10, 10, 10));
		textArea_venue.setAlignmentX(TextArea.LEFT_ALIGNMENT);
		textArea_venue.setFont(new Font("Times New Roman", Font.PLAIN, 14));
		textArea_venue.setBounds(27, 174, 310, 93);
		add(textArea_venue);
		
		JLabel lbldesc = new JLabel("Description of Event");
		lbldesc.setForeground(Color.WHITE);
		lbldesc.setFont(new Font("Times New Roman", Font.PLAIN, 14));
		lbldesc.setBounds(27, 295, 134, 23);
		add(lbldesc);
		
		JTextArea textArea_desc = new JTextArea();
		textArea_desc.setBorder(new EmptyBorder(10, 10, 10, 10));
		textArea_desc.setAlignmentX(TextArea.LEFT_ALIGNMENT);
		textArea_desc.setFont(new Font("Times New Roman", Font.PLAIN, 14));
		textArea_desc.setBounds(27, 318, 310, 93);
		add(textArea_desc);
		
		JLabel lbltime = new JLabel("Time of Event");
		lbltime.setForeground(Color.WHITE);
		lbltime.setFont(new Font("Times New Roman", Font.PLAIN, 14));
		lbltime.setBounds(429, 77, 89, 23);
		add(lbltime);
		
		JTextField textField_time = new JTextField();
		textField_time.setHorizontalAlignment(SwingConstants.LEFT);
		textField_time.setFont(new Font("Times New Roman", Font.PLAIN, 14));
		textField_time.setColumns(10);
		textField_time.setBorder(new EmptyBorder(0, 10, 0, 10));
		textField_time.setBounds(429, 100, 200, 30);
		add(textField_time);
		
		JLabel lblstatus = new JLabel("Status of Event");
		lblstatus.setForeground(Color.WHITE);
		lblstatus.setFont(new Font("Times New Roman", Font.PLAIN, 14));
		lblstatus.setBounds(429, 151, 89, 23);
		add(lblstatus);
		
		JTextField textField_status = new JTextField();
		textField_status.setHorizontalAlignment(SwingConstants.LEFT);
		textField_status.setFont(new Font("Times New Roman", Font.PLAIN, 14));
		textField_status.setColumns(10);
		textField_status.setBorder(new EmptyBorder(0, 10, 0, 10));
		textField_status.setBounds(429, 178, 200, 30);
		add(textField_status);
		
		JButton btnReset = new JButton("Reset");
		btnReset.setBackground(new Color(102, 255, 153));
		btnReset.setForeground(Color.WHITE);
		btnReset.setFont(new Font("Tahoma", Font.PLAIN, 16));
		btnReset.setFocusPainted(false);
		btnReset.setBounds(668, 475, 185, 40);
		add(btnReset);
		
		JButton btnSubmit = new JButton("Submit");
		btnSubmit.setBackground(new Color(102, 255, 153));
		btnSubmit.setForeground(Color.WHITE);
		btnSubmit.setFont(new Font("Tahoma", Font.PLAIN, 16));
		btnSubmit.setFocusPainted(false);
		btnSubmit.setBounds(441, 475, 185, 40);
		add(btnSubmit);
	}
	
	/**
	 * Launch the application.
	 */
	public static void main(String[] args) {
		EventQueue.invokeLater(new Runnable() {
			public void run() {
				try {
					JFrame frame = new JFrame();
					frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
					frame.setBounds(100, 100, 1400, 1000);
					frame.setExtendedState(JFrame.MAXIMIZED_BOTH);
					frame.getContentPane().setLayout(null);
					frame.setBackground(Color.GRAY);
					
					JPanel contentPane = new JPanel();
					contentPane.setBackground(SystemColor.windowBorder);
					contentPane.setBorder(new EmptyBorder(5, 5, 5, 5));
					contentPane.setLayout(null);
					contentPane.add(new EventFormPanel());
					frame.setContentPane(contentPane);
					
					
					frame.setVisible(true);
					
				} catch (Exception e) {
					e.printStackTrace();
				}
			}
		});
	}

}
