package com.instisoft.form.views;

import java.awt.Color;
import java.awt.Cursor;
import java.awt.EventQueue;
import java.awt.Font;
import java.awt.SystemColor;

import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JTextField;
import javax.swing.JToggleButton;
import javax.swing.SwingConstants;
import javax.swing.border.EmptyBorder;

import com.instisoft.utils.GUILookAndFeel;

public class FacultyFormPanel extends JPanel {
	
	private static final long serialVersionUID = 1L;

	private JTextField textField_Name;
	private JTextField textField_Id;
	
	/**
	 * Create the panel.
	 */
	public FacultyFormPanel() {
		
		setSize(1118, 550);
		setLayout(null);
		setBackground(null);
		setOpaque(false);
		
		
		JLabel lblName = new JLabel("Full Name");
		lblName.setFont(new Font("Times New Roman", Font.PLAIN, 14));
		lblName.setForeground(Color.WHITE);
		lblName.setBounds(27, 11, 200, 23);
		add(lblName);
		
		textField_Name = new JTextField();
		textField_Name.setHorizontalAlignment(SwingConstants.LEFT);
		textField_Name.setFont(new Font("Times New Roman", Font.PLAIN, 14));
		textField_Name.setColumns(10);
		textField_Name.setBorder(new EmptyBorder(0, 10, 0, 10));
		textField_Name.setBounds(27, 36, 200, 30);
		add(textField_Name);
		
		JLabel lblAutoGeneratedSerialNo = new JLabel("Auto generated Course Id");
		lblAutoGeneratedSerialNo.setForeground(Color.WHITE);
		lblAutoGeneratedSerialNo.setFont(new Font("Times New Roman", Font.PLAIN, 14));
		lblAutoGeneratedSerialNo.setBounds(438, 11, 157, 23);
		add(lblAutoGeneratedSerialNo);
		
		textField_Id = new JTextField();
		textField_Id.setEditable(false);
		textField_Id.setHorizontalAlignment(SwingConstants.LEFT);
		textField_Id.setFont(new Font("Times New Roman", Font.PLAIN, 14));
		textField_Id.setColumns(10);
		textField_Id.setBorder(new EmptyBorder(0, 10, 0, 10));
		textField_Id.setBounds(438, 36, 200, 30);
		add(textField_Id);
		
		JLabel lblCustomizeSno = new JLabel("Customize Course Id");
		lblCustomizeSno.setForeground(Color.WHITE);
		lblCustomizeSno.setFont(new Font("Times New Roman", Font.PLAIN, 14));
		lblCustomizeSno.setBounds(719, 11, 134, 23);
		add(lblCustomizeSno);
		
		ImageIcon toggleOnIcon = new ImageIcon("resources/toggle_button_ON.png");
		ImageIcon toggleOffIcon =new ImageIcon("resources/toggle_button_OFF.png");
		
		JToggleButton toggleButton = new JToggleButton("OFF");
		toggleButton.setHorizontalAlignment(SwingConstants.LEADING);
		toggleButton.setForeground(GUILookAndFeel.getThemeColor());
		toggleButton.setFont(new Font("Trebuchet MS", Font.BOLD, 16));
		toggleButton.setFocusable(false);
		toggleButton.setContentAreaFilled(false);
		toggleButton.setOpaque(false);
		toggleButton.setBorderPainted(false);
		toggleButton.setBounds(719, 32, 134, 35);
		toggleButton.setIcon(toggleOffIcon);
		toggleButton.addItemListener((event)->{
			
			if(toggleButton.isSelected()){
				toggleButton.setText("ON");
				toggleButton.setIcon(toggleOnIcon);
				textField_Id.setEditable(true);
				
				
			}
			else{
				toggleButton.setText("OFF");
				toggleButton.setIcon(toggleOffIcon);
				textField_Id.setEditable(false);
				textField_Id.setFocusable(false);
				textField_Id.transferFocus();
				
			}
		});
		toggleButton.setCursor(new Cursor(Cursor.HAND_CURSOR));
		add(toggleButton);
		
	}
	
	private void resetFields(){
		textField_Id.setText("");
		textField_Name.setText("");
		textField_Category.setText("");
		textField_Fee.setText("");
		textField_Faculty.setText("");
		textField_Classes.setText("");
		textField_Schedule.setText("");
		textArea_Desc.setText("");
	}
	
	/**
	 * Launch the application.
	 */
	public static void main(String[] args) {
		EventQueue.invokeLater(new Runnable() {
			public void run() {
				try {
					JFrame frame = new JFrame();
					frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
					frame.setBounds(100, 100, 1400, 1000);
					frame.setExtendedState(JFrame.MAXIMIZED_BOTH);
					frame.getContentPane().setLayout(null);
					frame.setBackground(Color.GRAY);
					
					JPanel contentPane = new JPanel();
					contentPane.setBackground(SystemColor.windowBorder);
					contentPane.setBorder(new EmptyBorder(5, 5, 5, 5));
					contentPane.setLayout(null);
					contentPane.add(new FacultyFormPanel());
					frame.setContentPane(contentPane);
					
					
					frame.setVisible(true);
					
				} catch (Exception e) {
					e.printStackTrace();
				}
			}
		});
	}

}
